name: easy_vote_backend
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  uuid: ^2.0.4
  json_annotation: ^3.0.0

dev_dependencies:
  json_serializable: ^3.2.0
  build_runner: ^1.0.0
  test: ^1.0.0
  aqueduct_test: ^1.0.0